"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const modal_1 = require("./modal");
const formActions_1 = require("./formActions");
const load_1 = require("./load");
const socket_1 = require("./socket");
const message_1 = require("./message");
document.addEventListener('DOMContentLoaded', load_1.loadMessageHistory);
message_1.chatSpaceWrapper.addEventListener('scroll', load_1.loadOnScroll);
socket_1.SOCKET.connectedSocket.addEventListener('message', socket_1.getMessage);
message_1.FORM.CURRENT.addEventListener('submit', socket_1.postMessage);
modal_1.authorizationModal.UI_ELEMENTS.form.addEventListener('submit', formActions_1.codeResponse);
modal_1.authorizationModal.UI_ELEMENTS.openButton.addEventListener('click', modal_1.authorizationModal.openHandler);
modal_1.authorizationModal.UI_ELEMENTS.main.addEventListener('click', modal_1.authorizationModal.closeHandler);
modal_1.settingsModal.UI_ELEMENTS.form.addEventListener('submit', formActions_1.setUsername);
modal_1.settingsModal.UI_ELEMENTS.openButton.addEventListener('click', modal_1.settingsModal.openHandler);
modal_1.settingsModal.UI_ELEMENTS.main.addEventListener('click', modal_1.settingsModal.closeHandler);
modal_1.acceptModal.UI_ELEMENTS.form.addEventListener('submit', formActions_1.saveToken);
modal_1.acceptModal.UI_ELEMENTS.openButton.addEventListener('click', modal_1.acceptModal.open);
